version: "3.2"
services:

  sql-server-db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
    environment:
      SA_PASSWORD: "testPassw0rd"
      ACCEPT_EULA: "Y"